### ISSUE TITLE
Captcha Solver Problem

### ISSUE THREAD

**Issue by thienha1** [Athlon1600/php-captcha-solver#1]
![Screenshot_2020-09-08-02-17-04-855_org mozilla firefox](https://user-images.githubusercontent.com/18132856/92413299-9ddc0380-f179-11ea-97c5-9363b89f2c2a.jpg)
I tried everything to call 2captcha API and still no hope it work

**Comment by Athlon1600** [comment]
can you look in your developer tools - console or network tabs, and see what you're getting back?
I am using the latest version of php-captcha-solver and it seems to work fine for me?
